### ISSUE TITLE
new buffer() deprecated since v6

### ISSUE THREAD

**Issue by roccomuso** [infusion/node-dhcp#31]
I saw the `package.json` denotes as node version `*`. But `new Buffer()` was deprecated since v6.

I recommend to use [safe-buffer](https://github.com/feross/safe-buffer) to have full-compatibility.

**Comment by infusion** [comment]
Thanks for the hint!

**Comment by roccomuso** [comment]
NB. `Buffer.alloc` was introduced with `Node v5.10.0`.

Not using `safe-buffer` means you have to choose whether to break older node versions or not.

If so I recommend also to change the `package.json` node version from `*` to `>=5.10.0`
