### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by nistorj** [infusion/node-dhcp#38]
HI,

Would it be possible to better handle requests that come in with options that are not present in the options.js file?

events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Unknown option 150)
    at Server.emit (events.js:171:17)
    at Server._getOptions (/usr/local/lib/node_modules/dhcp/lib/dhcp.js:206:16)
    at Server.sendOffer (/usr/local/lib/node_modules/dhcp/lib/dhcp.js:370:21)
    at Server.handleDiscover (/usr/local/lib/node_modules/dhcp/lib/dhcp.js:348:10)
    at Socket.<anonymous> (/usr/local/lib/node_modules/dhcp/lib/dhcp.js:91:16)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
root@spike:~/node-dhcp #

It would be handy to maybe have it print out an error saying: "unknown option <x>, value: <y>".

plx&thnx :>

**Comment by nistorj** [comment]
Yes, I think that's what I was trying to convey, a default case would be perfect.  :>

**Comment by infusion** [comment]
Hmm, I think it's hard to define a default case since all unimplemented options have different types. What I can think of instead of throwing an error I could just invoke the error handler, so you can catch these cases with `on("error")`

**Comment by nistorj** [comment]
that would be perfect, logging the info works perfectly fine too.  It's impossible to cover every use-case but we also don't want the system to die out when it can't handle something.  Never know what kind of junk devices request these days!

**Comment by infusion** [comment]
Yeah, you're absolutely right! I did it the hard way to see problems immediately while developing. But I will change it :)

**Comment by nistorj** [comment]
^--- best customer service right here.

**Comment by infusion** [comment]
Thanks :) v0.2.18 just landed on npm.
