### ISSUE TITLE
windows 10, basic example of dhcpd: needs to specify server ip

### ISSUE THREAD

**Issue by ccoenen** [infusion/node-dhcp#43]
I'm not sure if this is expected or not, on windows 10 with the example dhcpd from the readme, it will fail 

    .....\node_modules\dhcp\lib\dhcp.js:180
        throw new Error('Required option ' + Options.opts[req].config + ' does not have a value set');
        ^
    
    Error: Required option server does not have a value set
        at Server._getOptions (.....\node_modules\dhcp\lib\dhcp.js:180:17)
        at Server.sendOffer (.....\node_modules\dhcp\lib\dhcp.js:370:21)
        at Server.handleDiscover (.....\node_modules\dhcp\lib\dhcp.js:349:10)
        at Socket.<anonymous> (.....\node_modules\dhcp\lib\dhcp.js:91:16)
        at Socket.emit (events.js:182:13)
        at UDP.onMessage [as onmessage] (dgram.js:678:8)

The error goes away if I specify my computer's IP in createServer:

    var s = dhcp.createServer({
        server: '192.168.100.20', // my computer's local IP
        // rest unchanged

I went to dhcp.js around line 345 and tried reading `config('server')`, but it was simply `0`. I didn't find where _and if_ this should be set manually under normal circumstances.

If this is expected, I would like to request adding it to the readme. If this is unexpected, I would like find and squish that bug.

**Comment by ccoenen** [comment]
for reference: I'm using node.js 11.0.7 (current version at time of writing). NPM 6.4.1 and dhcp 0.2.18 from npm packages.

**Comment by infusion** [comment]
I'm reading the source to figure out what could go wrong on windows that it's not finding an entry on the object. This is really strange and you did nothing wrong, so it should be a bug somehow.

**Comment by infusion** [comment]
Does this also happen with `examples/server.js`? You should be able to execute without any problems. Here for me on OSX with node 11.5.0:

```
➜  examples git:(master) ✗ sudo node server.js
Server Listening: 0.0.0.0:67
```

**Comment by ccoenen** [comment]
interestingly, i can run the server example with no problem at all right from master. It also completes a full cycle until "BOUND" when I reset wifi on my smartphone.

**Comment by infusion** [comment]
Okay, then the example in the readme seems to be broken somehow. I'll look into that.

**Comment by ccoenen** [comment]
I verified that I have the same problem with `master`.

I just saw, server.js has also set the `server` config:

https://github.com/infusion/node-dhcp/blob/master/examples/server.js#L26

perhaps it's just missing from the minimal readme example.

**Comment by ccoenen** [comment]
funnily, I didn't alter that (so on my network this would be the wrong IP) yet it didn't create any problem as far as I can tell right now.

**Comment by infusion** [comment]
This does not throw an error since that option is sent to the client in the dhcp package only. The server is bound on INADDR_ANY per default.
I updated the readme, sorry for that mistake.

**Comment by ccoenen** [comment]
not a problem. I have a fine dhcpd running in JS right now. Many thanks for that :-)

I added `server` and also `broadcast` and `dns` to my script and it works spectacularly!

Next up: auto configure new clients (think: `ssh-copy-id` and setting serialised hostnames for a bunch of raspberry-pis). I'll let you know how it goes!
