### ISSUE TITLE
Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by nistorj** [infusion/node-dhcp#44]
Hi,

Had a weird issue happen today with the following output:

  flags: 0,
  ciaddr: '0.0.0.0',
  yiaddr: '0.0.0.0',
  siaddr: '0.0.0.0',
  giaddr: '0.0.0.0',
  chaddr: '98-4B-E1-6D-20-51',
  sname: '',
  file: '',
  magicCookie: 1669485411,
  options:
   { '12': 'finnix',
     '53': 1,
     '55': [ 1, 28, 2, 3, 15, 6, 119, 12, 44, 47, 26, 121, 42 ] } }
/home/nistor/node_modules/dhcp/lib/dhcp.js:302
      const ip = this._state[oldestMac].address;
                                        ^
TypeError: Cannot read property 'address' of undefined
    at Server._selectAddress (/home/nistor/node_modules/dhcp/lib/dhcp.js:302:41)
    at Server.handleDiscover (/home/nistor/node_modules/dhcp/lib/dhcp.js:343:26)
    at Socket.<anonymous> (/home/nistor/node_modules/dhcp/lib/dhcp.js:91:16)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)

What is interesting is that it doesn't happen all that often from that host.  Any idea?

**Comment by infusion** [comment]
Thanks for the issue. What really strange is that this can actually happen. But it depends on your config. So I added a check to go into that branch only if it is save to do so.
