### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by jgroom33** [infusion/node-dhcp#46]
A Dockerfile should be added that allows this package to run as a container

**Comment by infusion** [comment]
This is a nice idea, I would propose something like

```
FROM node:10

USER dhcp

EXPOSE 69

WORKDIR /home/dhcp

RUN mkdir -p /home/dhcp
RUN npm install dhpc

CMD [ "node", "node_modules/dhcp/bin/dhcpd-cli.js" ]
```

The remaining question is, how could we pass all the options to the dhcpd daemon. Either via env vars, or all within the docker file. What do you think?

Robert

**Comment by jgroom33** [comment]
This is an option:

Change CMD to
ENTRYPOINT [ "node", "node_modules/dhcp/bin/dhcpd-cli.js" ]

Then the options can be passed during the docker run command.

It's also possible to leave it as CMD and the docker run command could override the entire command (with the options)

Does the current code support environment variables? I presume the most popular use case is to modify the server JavaScript. Possibly, there are use cases that would run multiple docker DHCP containers with different ports exposed. That use case could benefit from environment variables. But the multi container use case could also use a js file for each iteration. That file could be volume mapped during docker run.

**Comment by infusion** [comment]
The code does not handle env vars at the moment. Everything is passed as argument at the moment. Do you think we should plan for the multiple installation case already or keep it simple for now?
BTW: Do you know if EXPOSE exposes UDP ports as well?

**Comment by jgroom33** [comment]
The user can figure out how to run multiple. No code changes should be required.
Assume they have dhcpserver1.js and dhcpserver2.js  ... each would have the options specified for that server.
They could run each with:
`docker run -v dhcpserver1.js:/expected/config/path/config.js`

For broadcast DHCP, I think it will be necessary to docker run with --net=host

In cases where there is a router configured for DHCP forwarding, --net=host should not be necessary.

Ports 67/68 are use for DHCP.... 69 is tftp
https://en.m.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol

It's possible to expose udp: https://stackoverflow.com/questions/27596409/how-do-i-expose-a-udp-port-on-docker

**Comment by infusion** [comment]
Port 69 was a typo, sorry. I updated the dockerfile proposal from above. Do you need some additions to that file?
You proposal of running multiple instances looks good.

**Comment by jgroom33** [comment]
I just tried this and it is close:

```Dockerfile
FROM node:10

WORKDIR /usr/src/app

COPY . .

RUN npm install

EXPOSE 67/udp

CMD [ "node", "bin/dhcpd-cli.js" ]
```

**Comment by infusion** [comment]
If you want, you can send it together with a little note in the readme as a PR. 

Does docker create the workdir itself?

**Comment by jgroom33** [comment]
i just tried the above and it does create the directory

**Comment by jgroom33** [comment]
it might be possible to have a second dockerfile with the client.  Then the two containers could be connected and tested together.
