### ISSUE TITLE
bootFile: function(){} arguments not passed

### ISSUE THREAD

**Issue by mStirner** [infusion/node-dhcp#50]
Hello, 

the options function doesnt work.
The arguments are not passed.

```js
// merge options
let options = merge({
  range: ["172.16.0.100", "172.16.0.200"],
  netmask: "255.255.255.0",
  router: ["172.16.0.254"],
 ...
  domainName: "magic-boot.lan",
  bootFile: function (req, res) {

  // req & res = undefined

    console.log("-- BOOTFILE", arguments);
    return "pxelinux.0"

  }
}, config.options);
  ````

So the example/server.js dosnt work neither:

>if (req.clientId === 'foo bar') {
>         ^
>TypeError: Cannot read property 'clientId' of undefined

Problem seems for me this line: 
https://github.com/infusion/node-dhcp/blob/master/lib/dhcp.js#L144

**Comment by infusion** [comment]
Thanks a lot for bringing this up! I fixed it with the latest commit. Could you please test it? If it works, I will push a new release on npm.

**Comment by mStirner** [comment]
Hey, sorry, i was very bussy the last two days, and could find any time to test it, until now.
Seems to work, but you have a console.log (for debugging?) here: 
https://github.com/infusion/node-dhcp/blob/master/lib/dhcp.js#L88

Thanks, for the fix!

**Comment by infusion** [comment]
Thanks for pointing out the console.log, removed
