### ISSUE TITLE
Custom options (209, syslinux config file)

### ISSUE THREAD

**Issue by mStirner** [infusion/node-dhcp#51]
I need to tell pxelinux/syslinux what config file should be loaded, this is DHCP option 209.
(https://wiki.syslinux.org/wiki/index.php?title=PXELINUX#DHCP_options)

Could there be a helper function to define custom options ?
This would solve the problem for "unknown options" #17  too, 
just write a empty function for them

**Comment by infusion** [comment]
Pretty good idea, thanks! I'll implement it :)

**Comment by infusion** [comment]
Hmm, I implemented a custom option behavior like this:

```
  customOption: function(opt) {
    if (opt == 209) {
      return {
        name: 'UTF8',
        type: 'IPs',
        config: 'nameServer'
      };
    }
    return null;
  },
```

But I must say, I don't like it, since the options are quite static. I added the PXE options for now and add a new static method to add more options from the userspace, but not in an error-handling behavior.

**Comment by infusion** [comment]
Okay, I added a static method to add more options like so on runtime:

```
var dhcpd = require('dhcp');
dhcpd.addOption(209, { 
    name: 'PXE Config File',
    type: 'ASCII',
    config: 'pxeConfigFile'
  });
```

**Comment by mStirner** [comment]
I test it and give you feedback if nots working.
Many thanks for your effort
