### ISSUE TITLE
In example typo

### ISSUE THREAD

**Issue by XantheFIN** [infusion/node-dhcp#53]
Your README.md issues
For noobs big headache.

Running Sierra macOS here

```
Simple DHCP Server
var dhcp = require('dhcp');

var s = dhcpd.createServer({
```

**ReferenceError: dhcpd is not defined**

Your website you wrote this example:

```
var dhcpd = require('dhcp');

var s = dhcpd.createServer({
```

Then we get

```
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES 0.0.0.0:67
    at dgram.js:321:18
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
    at dgram.js:322:14
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 67
}
```

What next?

**Comment by infusion** [comment]
As you might know, dhcp uses port 67, which is below 1024 and thus needs sudo privileges. Start the program with
$ sudo node server.js

**Comment by XantheFIN** [comment]
Yes sorry that was it why didn't run. Now did understand Troubleshooting section already told that. Excuse me.

This noobie is so happy.


Still though other device not getting ip settings.

**Comment by infusion** [comment]
Can you post your config? Is there another dhcp server (such as wifi router) on your net?

Glad I made a noob happy ;)

**Comment by infusion** [comment]
Fixed the typo, thx

**Comment by XantheFIN** [comment]
Sure!

`var dhcpd = require('dhcp');

var s = dhcpd.createServer({
  // System settings
  range: [
    "1.1.1.12", "1.1.1.99"
  ],
  forceOptions: ['hostname'], // Options that need to be sent, even if they were not requested
  randomIP: true, // Get random new IP from pool instead of keeping one ip
  static: {
    "11:22:33:44:55:66": "1.1.1.88"
  },

  // Option settings (there are MUCH more)
  netmask: '255.255.255.0',
  router: [
    '1.1.1.10'
  ],
  dns: ["8.8.8.8", "8.8.4.4"],
  hostname: "xiaotec.nat",
  broadcast: '1.1.1.255',
  server: '1.1.1.11', // This is us
  bootFile: function (req, res) {

    // res.ip - the actual ip allocated for the client

    if (req.clientId === 'foo bar') {
      return 'x86linux.0';
    } else {
      return 'x64linux.0';
    }
  }
});

s.listen();`


From wifi to ethernet (macOS) --> Switch -> PS3

When click InternetSharing it gets almost like instant ip but something now missing. I did try defaults and wont give.  Ethernet has manual ip4 config in System preferences.

**Comment by XantheFIN** [comment]
Sure!

Wifi (income) (macOS ) Ethernet -> Switch -> PS3 (as test i see nicely how it goes)
Via Internet Sharing i get almost instant those defaults.

`var dhcpd = require('dhcp');

var s = dhcpd.createServer({
  // System settings
  range: [
    "1.1.1.12", "1.1.1.99"
  ],
  forceOptions: ['hostname'], // Options that need to be sent, even if they were not requested
  randomIP: true, // Get random new IP from pool instead of keeping one ip
  static: {
    "11:22:33:44:55:66": "1.1.1.88"
  },

  // Option settings (there are MUCH more)
  netmask: '255.255.255.0',
  router: [
    '1.1.1.10'
  ],
  dns: ["8.8.8.8", "8.8.4.4"],
  hostname: "nat",
  broadcast: '1.1.1.255',
  server: '1.1.1.11', // This is us
  bootFile: function (req, res) {

    // res.ip - the actual ip allocated for the client

    if (req.clientId === 'foo bar') {
      return 'x86linux.0';
    } else {
      return 'x64linux.0';
    }
  }
});

s.listen();`

Should change dns to own too after. Anyway i tried default example config too. But no ip to PS3

**Comment by infusion** [comment]
Could you please put the following in front of `s.listen()`:

```
s.on('message', function (data) {
consol.log(data);
});
s.on('error', function (err) {
consol.log(err);
});
```

**Comment by infusion** [comment]
This way you get details on what is actually going on.

**Comment by XantheFIN** [comment]
My terminal doesn't produce any output with that.

Must still be some problem on my side.. 



Last part of earlier with new code.

`    // res.ip - the actual ip allocated for the client

    if (req.clientId === 'foo bar') {
      return 'x86linux.0';
    } else {
      return 'x64linux.0';
    }
  }
});

s.on('message', function (data) {
    consol.log(data);
    });
s.on('error', function (err) {
consol.log(err);
});

s.on('bound', function (data) {
    consol.log("Client got the following config:", data);
    });    
    

s.listen();`

**Comment by infusion** [comment]
There is a typo. It must read `console` with E at the end. Anyway, does your PS3 actually produce DHCP messages that can be received by the server? Do you restart the PS3 when the server is listening? To figure out if your computer is actually receiving any DHCP data, run wireshark on the network interface and see if there is any DHCP broadcast coming in.

**Comment by XantheFIN** [comment]
![Screen Shot 2019-07-19 at 1 28 27 PM](https://user-images.githubusercontent.com/6132150/61529143-518bac80-aa29-11e9-917d-1b886bf3fc5a.png)
Yes there is. Instantly i turn PS3 Enable internet it keeps trying to get info as far as i see.

**Comment by XantheFIN** [comment]
![Screen Shot 2019-07-19 at 1 40 56 PM](https://user-images.githubusercontent.com/6132150/61529832-096d8980-aa2b-11e9-8b1c-71211a8d1ac0.png)
Wait a minute...

**Comment by infusion** [comment]
Ahh, that looks like progress! Is this the only packet you got? If so, could you have a look in wireshark again, if the sent message actually arrives the network?

**Comment by XantheFIN** [comment]
It keeps repeating.


Woo now it got through!


```
var dhcpd = require('dhcp');

var s = dhcpd.createServer({
  // System settings
  range: [
    "1.1.1.13", "1.1.1.99"
  ],
  forceOptions: ['hostname'], // Options that need to be sent, even if they were not requested
  randomIP: true, // Get random new IP from pool instead of keeping one ip
  static: {
    "11:22:33:44:55:66": "1.1.1.88"
  },

  // Option settings (there are MUCH more)
  netmask: '255.255.255.0',
  router: [
    '1.1.1.1'
  ],
  dns: ["8.8.8.8", "8.8.4.4"],
  hostname: "natfucker",
  broadcast: '1.1.1.1',
  server: '1.1.1.12', // This is us
  bootFile: function (req, res) {

    // res.ip - the actual ip allocated for the client

    if (req.clientId === 'foo bar') {
      return 'x86linux.0';
    } else {
      return 'x64linux.0';
    }
  }
});

s.on('message', function (data) {
console.log(data);
});
    
s.on('error', function (err) {
console.log(err);
});

s.on('bound', function (data) {
console.log("Client got the following config:", data);
});    

console.log('hello world');    

s.listen();
```

and.. did again change this setting from System Preferences.

![Screen Shot 2019-07-19 at 2 29 47 PM](https://user-images.githubusercontent.com/6132150/61532275-01651800-aa32-11e9-9173-be52134752f6.png)



log:

{
  op: 1,
  htype: 1,
  hlen: 6,
  hops: 0,
  xid: 4153204749,
  secs: 0,
  flags: 0,
  ciaddr: '0.0.0.0',
  yiaddr: '0.0.0.0',
  siaddr: '0.0.0.0',
  giaddr: '0.0.0.0',
  chaddr: '00-1F-censor:)',
  sname: '',
  file: '',
  magicCookie: 1669485411,
  options: {
    '50': '1.1.1.13',
    '53': 3,
    '54': '1.1.1.11',
    '55': [ 1, 3, 15, 6 ],
    '60': 'PS3',
    '61': '\u0001'
  }
}
Client got the following config: {
  '00-censor:)': {
    address: '1.1.1.95',
    leasePeriod: 86400,
    server: '1.1.1.12',
    state: 'BOUND',
    bindTime: 2019-07-19T11:29:35.710Z
  }
}


Thanks quick open help! I will today still keep open this issue and close this as solved after i verified it working correctly some time. :) 

Noobie super happy ^^,

**Comment by infusion** [comment]
YES! =) This is good news. So the problem was your local config?

**Comment by XantheFIN** [comment]
after reboot


```
Error: send EHOSTDOWN 1.1.1.1:68
    at SendWrap.afterSend [as oncomplete] (dgram.js:678:11) {
  errno: 'EHOSTDOWN',
  code: 'EHOSTDOWN',
  syscall: 'send',
  address: '1.1.1.1',
  port: 68
}
```


```
Error: send EHOSTDOWN 1.1.1.1:68
    at SendWrap.afterSend [as oncomplete] (dgram.js:678:11) {
  errno: 'EHOSTDOWN',
  code: 'EHOSTDOWN',
  syscall: 'send',
  address: '1.1.1.1',
  port: 68
}


```


Wierd. Well at least it works sometime after doing something.. Just need learn what it was in the end.
