### ISSUE TITLE
htype + hlen missing checks and hard coded hlen on getMAC

### ISSUE THREAD

**Issue by gregorybrzeski** [infusion/node-dhcp#7]
https://github.com/infusion/node-dhcp/blob/master/lib/seqbuffer.js#L157

In getMAC code assumes that chaddr is of length 6 however it doesn't check htype and hlen fields before to make this assumption true.

Maybe allow only htype === 1 and hlen === 6 ?

Then in getMAC use hlen value instead of hardcoded value of 6 ?

**Comment by infusion** [comment]
That's a good point. I assumed htype to be ethernet and hlen=6 to be a mac address. But validating this should definitely take place. Thanks!

**Comment by infusion** [comment]
Okay I ignore htype, but check if hlen is <= 16byte, since this is the maximum number the hardware address can have. Do you see any problems on this kind of fix and would like to see htype === 1 and hlen === 6?

**Comment by gregorybrzeski** [comment]
If you allow any htype (other than 1 that is Ethernet), then you have to modify code in addMAC() as well. Currently addMAC() also assumes input format to be htype === 1 and hlen === 6 (hardcoded).

https://github.com/infusion/node-dhcp/blob/18597eb62965b107ea2b9539dc16f7755615a3ff/lib/seqbuffer.js#L146

In my opinion it's highly unlikely that it's going to be used in other networks than Ethernet, therefore I would limit it to just htype === 1 to simplify implementation. I have no knowledge what other implementation issues are going to arise when allowing htypes other than 1 (ethernet).

Looking at the hlen <= 16byte check, I would move it higher before the toString().

You have also added number of checks and throwing Errors, but are you catching them ? ;-)

**Comment by infusion** [comment]
You're right, limiting to ethernet & hlen=6 for mac addresses makes most sense. I've fixed that and also added the exception handler. Thanks for pointing this out. 4 eyes (or in general 2*k eyes) see more than 2. v0.2.5 Has both fixes now.

**Comment by infusion** [comment]
Does the change/fix fulfill your requirements?
