### ISSUE TITLE
dhcp cli command fails on machine with multiple network interfaces

### ISSUE THREAD

**Issue by apexearth** [infusion/node-dhcp#8]
On my windows PC I have two NICs and when I try to run the client (`dhcp`) from command line I get an error because there are too many network interfaces. 

```
Error: Too many network interfaces, set mac address manually:
        client = dhcp.createClient({mac: "12:23:34:45:56:67"});
    at Client.config (C:\Users\cjacobs\AppData\Roaming\npm\node_modules\dhcp\lib\dhcp.js:526:23)
    at Client.sendDiscover (C:\Users\cjacobs\AppData\Roaming\npm\node_modules\dhcp\lib\dhcp.js:577:20)
    at Object.<anonymous> (C:\Users\cjacobs\AppData\Roaming\npm\node_modules\dhcp\bin\dhcp-cli.js:32:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

I cannot proceed from CLI because there is no command line option for MAC addresses.

**Comment by apexearth** [comment]
This isn't a high priority for me as I'm not using the feature. I happened to notice it during testing.

**Comment by infusion** [comment]
Since all arguments are passed as options, it should (haven't tested it though) work with `--mac 12:23:34:45:56:67`

**Comment by apexearth** [comment]
It doesn't seem to work for me.

The problem seems to be in the way the cli creates the client.

```
var client = dhcp.createClient({
  features: argv._
});
```

If I change that to `var client = dhcp.createClient(argv);` then it works ok.

**Comment by infusion** [comment]
Hmm, no the features key is needed in order to make the client request for the options/features. I think hard-coding `--mac` in `bin/dhcp-cli.js` for the moment is quite okay.

Just for curiosity: What are you building with the dhcp package? :)

**Comment by infusion** [comment]
Okay, I just implemented to make it work like this:

```
dhcp hostname --mac 1234556
```

The normal list is (like hostname) is passed to '_' via minimist and mac is passed as option. I'll push it in a few minutes.

**Comment by apexearth** [comment]
Thanks, I was looking for something to help assign DHCP to many devices in a private development network. I work a lot with Node.js so I would hoping something might have been created for it. Then I found this on NPM. :+1:
